import { ScenePreset } from "@/types/mockup";

export const SCENE_PRESETS: ScenePreset[] = [
  {
    id: "single-browser",
    name: "Browser",
    description: "Un navegador Safari centrado",
    canvasWidth: 900,
    canvasHeight: 600,
    padding: 80,
    background: { type: "gradient", from: "#6366f1", to: "#ec4899", direction: 135 },
    layers: [
      {
        device: "safari",
        x: 0,
        y: 0,
        scale: 1,
        rotateX: 0,
        rotateY: 0,
        rotateZ: 0,
        browserTheme: "light",
        browserUrl: "",
        zIndex: 1,
      },
    ],
  },
  {
    id: "single-phone",
    name: "iPhone",
    description: "Un iPhone 15 centrado",
    canvasWidth: 800,
    canvasHeight: 600,
    padding: 80,
    background: { type: "gradient", from: "#0ea5e9", to: "#22d3ee", direction: 135 },
    layers: [
      {
        device: "iphone15",
        x: 0,
        y: 0,
        scale: 0.5,
        rotateX: 0,
        rotateY: 0,
        rotateZ: 0,
        browserTheme: "light",
        browserUrl: "",
        zIndex: 1,
      },
    ],
  },
  {
    id: "hero-section",
    name: "Hero Section",
    description: "Browser con perspectiva 3D para landing pages",
    canvasWidth: 1000,
    canvasHeight: 650,
    padding: 60,
    background: { type: "gradient", from: "#1e1e1e", to: "#434343", direction: 180 },
    layers: [
      {
        device: "safari",
        x: 0,
        y: 20,
        scale: 0.9,
        rotateX: 12,
        rotateY: 0,
        rotateZ: 0,
        browserTheme: "dark",
        browserUrl: "",
        zIndex: 1,
      },
    ],
  },
  {
    id: "app-store",
    name: "App Store",
    description: "iPhone centrado para screenshots de App Store",
    canvasWidth: 900,
    canvasHeight: 600,
    padding: 80,
    background: { type: "gradient", from: "#667eea", to: "#764ba2", direction: 135 },
    layers: [
      {
        device: "iphone15",
        x: 0,
        y: 0,
        scale: 0.5,
        rotateX: 0,
        rotateY: 0,
        rotateZ: 0,
        browserTheme: "light",
        browserUrl: "",
        zIndex: 1,
      },
    ],
  },
  {
    id: "twitter-card",
    name: "Twitter Card",
    description: "Formato 2:1 para compartir en Twitter/X",
    canvasWidth: 1200,
    canvasHeight: 600,
    padding: 80,
    background: { type: "gradient", from: "#6366f1", to: "#8b5cf6", direction: 135 },
    layers: [
      {
        device: "safari",
        x: 0,
        y: 10,
        scale: 0.85,
        rotateX: 5,
        rotateY: 0,
        rotateZ: 0,
        browserTheme: "light",
        browserUrl: "",
        zIndex: 1,
      },
    ],
  },
  {
    id: "multi-device",
    name: "Multi Device",
    description: "MacBook + iPhone lado a lado",
    canvasWidth: 1100,
    canvasHeight: 650,
    padding: 80,
    background: { type: "gradient", from: "#10b981", to: "#06b6d4", direction: 135 },
    layers: [
      {
        device: "macbook",
        x: -120,
        y: 0,
        scale: 0.7,
        rotateX: 0,
        rotateY: 0,
        rotateZ: 0,
        browserTheme: "light",
        browserUrl: "",
        zIndex: 1,
      },
      {
        device: "iphone15",
        x: 280,
        y: 40,
        scale: 0.45,
        rotateX: 0,
        rotateY: 0,
        rotateZ: 0,
        browserTheme: "light",
        browserUrl: "",
        zIndex: 2,
      },
    ],
  },
];
